config/routes.rb
Rails.application.routes.draw do
  resources :saledetails
  resources :sales
  devise_for :users
  get 'purchases/new'
  get 'purchases/index'
  get 'purchases/show'
  resources :bills
  resources :categories
 get '/addbill' => 'bills#new'
 root 'homes#index'  
 get '/dashboard' => 'items#index'
 get '/add' =>'admins#new'
 resources :categories
 resources :products
 resources :customers
 resources :purchases
 get 'stock', to: 'stock#index'
 get 'purchase', to: 'purchase#index'
 get 'customer', to: 'customer#index'
resources :bills, only: [:new, :create, :show]
# config/routes.rb
resources :posts

# resources :bills do
#  resources :bill_details
#end

 resources :admins
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
      user ||= User.new 
    # guest user (not logged in)
      can :read, :all
       # Add more abilities based on your requirements
 
    
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
   
    validates :email, presence: true
    validates :password, presence: true
    has_secure_password
end

app/models/bill.rb
class Bill < ApplicationRecord
    has_many :bill_details
    has_many :products, through: :bill_details

    def bill_details_attributes=(bill_attr)
        bill_attr.each do |i, bill_at|
            self.bill_details.build(bill_at)
        end
    end     
    # has_many :bill_details, dependent: :destroy

    # accepts_nested_attributes_for :bill_details,
    #                               allow_destroy: true,
    #                               reject_if: :all_blank
end
    

app/models/bill_detail.rb
class BillDetail < ApplicationRecord
  belongs_to :product
  belongs_to :bill
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :image
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :bill_details
  has_many :bills, through: :bill_details
end

app/models/sale.rb
class Sale < ApplicationRecord
    has_many :saledetails, dependent: :destroy, inverse_of: :sale
    accepts_nested_attributes_for :saledetails, allow_destroy: true, reject_if: :all_blank  
end

app/models/saledetail.rb
class Saledetail < ApplicationRecord
  belongs_to :product
  belongs_to :sale
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/saledetails_controller.rb
class SaledetailsController < ApplicationController
  before_action :set_saledetail, only: %i[ show edit update destroy ]

  # GET /saledetails or /saledetails.json
  def index
    @saledetails = Saledetail.all
  end

  # GET /saledetails/1 or /saledetails/1.json
  def show
  end

  # GET /saledetails/new
  def new
    @saledetail = Saledetail.new
  end

  # GET /saledetails/1/edit
  def edit
  end

  # POST /saledetails or /saledetails.json
  def create
    @saledetail = Saledetail.new(saledetail_params)

    respond_to do |format|
      if @saledetail.save
        format.html { redirect_to saledetail_url(@saledetail), notice: "Saledetail was successfully created." }
        format.json { render :show, status: :created, location: @saledetail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @saledetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /saledetails/1 or /saledetails/1.json
  def update
    respond_to do |format|
      if @saledetail.update(saledetail_params)
        format.html { redirect_to saledetail_url(@saledetail), notice: "Saledetail was successfully updated." }
        format.json { render :show, status: :ok, location: @saledetail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @saledetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saledetails/1 or /saledetails/1.json
  def destroy
    @saledetail.destroy!

    respond_to do |format|
      format.html { redirect_to saledetails_url, notice: "Saledetail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saledetail
      @saledetail = Saledetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def saledetail_params
      params.require(:saledetail).permit(:product_id, :sale_id, :quantity, :price_per_unit, :total_price)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sale_helper.rb
module SaleHelper
end

app/helpers/saledetails_helper.rb
module SaledetailsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/saledetails/_form.html.erb
<%= form_with(model: saledetail) do |form| %>
  <% if saledetail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(saledetail.errors.count, "error") %> prohibited this saledetail from being saved:</h2>

      <ul>
        <% saledetail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :sale_id, style: "display: block" %>
    <%= form.text_field :sale_id %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :price_per_unit, style: "display: block" %>
    <%= form.number_field :price_per_unit %>
  </div>

  <div>
    <%= form.label :total_price, style: "display: block" %>
    <%= form.number_field :total_price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/saledetails/_saledetail.html.erb
<div id="<%= dom_id saledetail %>">
  <p>
    <strong>Product:</strong>
    <%= saledetail.product_id %>
  </p>

  <p>
    <strong>Sale:</strong>
    <%= saledetail.sale_id %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= saledetail.quantity %>
  </p>

  <p>
    <strong>Price per unit:</strong>
    <%= saledetail.price_per_unit %>
  </p>

  <p>
    <strong>Total price:</strong>
    <%= saledetail.total_price %>
  </p>

</div>

app/views/saledetails/edit.html.erb
<h1>Editing saledetail</h1>

<%= render "form", saledetail: @saledetail %>

<br>

<div>
  <%= link_to "Show this saledetail", @saledetail %> |
  <%= link_to "Back to saledetails", saledetails_path %>
</div>

app/views/saledetails/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Saledetails</h1>

<div id="saledetails">
  <% @saledetails.each do |saledetail| %>
    <%= render saledetail %>
    <p>
      <%= link_to "Show this saledetail", saledetail %>
    </p>
  <% end %>
</div>

<%= link_to "New saledetail", new_saledetail_path %>

app/views/saledetails/new.html.erb
<h1>New saledetail</h1>

<%= render "form", saledetail: @saledetail %>

<br>

<div>
  <%= link_to "Back to saledetails", saledetails_path %>
</div>

app/views/saledetails/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @saledetail %>

<div>
  <%= link_to "Edit this saledetail", edit_saledetail_path(@saledetail) %> |
  <%= link_to "Back to saledetails", saledetails_path %>

  <%= button_to "Destroy this saledetail", @saledetail, method: :delete %>
</div>